let canvas;
let world;
let chicken;
let movableObject;
let imagesToLoad = 0;
let imagesLoaded = 0;
let percent;
let EndbossChickenHit = true;
let startGameVar = true;
let gameWin = false;
let gameLost = false;
